version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signup-task
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm start